### ISSUE TITLE
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

### ISSUE THREAD

**Issue by Bill-JLN** [yeyupiaoling/AudioClassification-Pytorch#1]
我更改了输入为tensorfloat但是还是报相似的错误
![QQ图片20211206154826](https://user-images.githubusercontent.com/74843710/144807531-77d63269-2d0d-489c-b329-7184df7b9b18.png)

**Comment by yeyupiaoling** [comment]
类型错误，你有改吗？没看到。你这边修改了，你拉下最新代码试试。

**Comment by Bill-JLN** [comment]
我等会把最新的代码拉一下改一下

**Comment by yeyupiaoling** [comment]
主要是这里：https://github.com/yeyupiaoling/AudioClassification-Pytorch/blob/017d3982485a954e2f1df69b681181080889da60/reader.py#L22

https://github.com/yeyupiaoling/AudioClassification-Pytorch/blob/017d3982485a954e2f1df69b681181080889da60/infer.py#L22

**Comment by Bill-JLN** [comment]
这两行改成float64吗

**Comment by yeyupiaoling** [comment]
这是改好的。就是float32

**Comment by Bill-JLN** [comment]
行，我试试

**Comment by Bill-JLN** [comment]
解决了，跪谢大佬
