### ISSUE TITLE
配置文件中的数据预处理参数有问题， feature_method: 'Spectrogram'，报错，参数解析有问题

### ISSUE THREAD

**Issue by zsffuture** [yeyupiaoling/AudioClassification-Pytorch#10]
如题，在数据预处理中选择了Spectrogram，原始的是MelSpectrogram没问题，但是选择了Spectrogram就报错，从错误看是数据解析有问题，具体如下，希望大神更新一下
![1673318963603](https://user-images.githubusercontent.com/39027951/211450666-5e851edc-9027-4166-ae54-802bacc7513c.png)

**Comment by yeyupiaoling** [comment]
函数变了，里面的参数也变了，所以你要再配置参数文件里面改对应的参数名。

**Comment by zsffuture** [comment]
> 函数变了，里面的参数也变了，所以你要再配置参数文件里面改对应的参数名。

参数可以配置，但是参数的值如何设置合适呢？大神能不能有个样例在配置文件里，注释一下

**Comment by yeyupiaoling** [comment]
其他方法直接参考默认参数吧
