### ISSUE TITLE
A same torchaudio warning issued repeatedly in trainning and infering

### ISSUE THREAD

**Issue by sywee** [yeyupiaoling/AudioClassification-Pytorch#11]
I'm so appreciated for your excelent work of this project that help me a lot in my learning in the audio AI field.  As mentioned above, the torchaudio warning showed as following:

`UserWarning: At least one mel filterbank has all zero values. The value for `n_mels` (64) may be set too high. Or, the value for `n_freqs` (513) may be set too low.`

Whether the model's accuracy is affected by the issue is my most concern. Can you help me please?

**Comment by yeyupiaoling** [comment]
这个警告应该不影响模型的准确率，分类准确率也在90%以上。
至于这个警告，我也尝试修改n_melsn参数，并不能解决。

**Comment by sywee** [comment]
> 这个警告应该不影响模型的准确率，分类准确率也在90%以上。 至于这个警告，我也尝试修改n_melsn参数，并不能解决。

much thanks
