### ISSUE TITLE
How to run with features MFCC

### ISSUE THREAD

**Issue by JxuHenry** [yeyupiaoling/AudioClassification-Pytorch#12]
I can't runing with MFCC features

My config:
dataset_conf:
  batch_size: 32
  num_class: 10
  num_workers: 8
  min_duration: 0.5
  chunk_duration: 3
  do_vad: False
  sample_rate: 16000
  use_dB_normalization: True
  target_dB: -20
  train_list: 'dataset/train_list.txt'
  test_list: 'dataset/test_list.txt'
  label_list_path: 'dataset/label_list.txt'

preprocess_conf:
  feature_method: 'MFCC'

feature_conf:
  sample_rate: 16000
  n_mfcc: 40
  melkwargs:
    n_fft: 1024
    hop_length: 320
    win_length: 1024
    f_min: 50.0
    f_max: 14000.0
    n_mels: 64

optimizer_conf:
  learning_rate: 0.001
  weight_decay: 1e-6

model_conf:
  embd_dim: 192
  channels: 256

train_conf:
  max_epoch: 30
  log_interval: 10

use_model: 'ecapa_tdnn'

RuntimeError: Given groups=1, weight of size [256, 64, 5], expected input[32, 40, 151] to have 64 channels, but got 40 channels instead

**Comment by yeyupiaoling** [comment]
https://github.com/yeyupiaoling/AudioClassification-Pytorch/blob/77b7708a72f6e68a653c53960cdb7980d04d99e9/macls/data_utils/featurizer.py#L58

to

```
return self._feature_conf.n_mfcc
```

**Comment by JxuHenry** [comment]
> https://github.com/yeyupiaoling/AudioClassification-Pytorch/blob/77b7708a72f6e68a653c53960cdb7980d04d99e9/macls/data_utils/featurizer.py#L58
> 
> to
> 
> ```
> return self._feature_conf.n_mfcc
> ```

Thank you very mach ！
