### ISSUE TITLE
没有 PANNS 模型

### ISSUE THREAD

**Issue by ByteTuxiaobei** [yeyupiaoling/AudioClassification-Pytorch#15]
缺少 readme 中提到的 PANNS 模型

**Comment by ByteTuxiaobei** [comment]
找到模型参数了，应该是 ['EcapaTdnn', 'PANNS_CNN6', 'PANNS_CNN10', 'PANNS_CNN14', 'Res2Net', 'ResNetSE', 'TDNN']

建议更新配置文件夹说明与readme

**Comment by yeyupiaoling** [comment]
好的，有空更新一下。
