### ISSUE TITLE
自选数据集训练报错

### ISSUE THREAD

**Issue by Fatcat688** [yeyupiaoling/AudioClassification-Pytorch#21]
你好，我在使用自己的数据集进行训练时，出现了以下报错，请问要怎么解决呢？
size mismatch for fc.weight: copying a param with shape torch.Size([10, 192]) from checkpoint, the shape in current model is torch.Size([6, 192]).
size mismatch for fc.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([6]).
[用自己的数据集训练报错.txt](https://github.com/yeyupiaoling/AudioClassification-Pytorch/files/12487756/default.txt)

**Comment by yeyupiaoling** [comment]
你是使用了预训练模型吗？

**Comment by Fatcat688** [comment]
是的，用了预训练模型

**Comment by Fatcat688** [comment]
已经解决这个问题了，谢谢大佬！我把原来数据集的模型文件删掉就可以了
