### ISSUE TITLE
can flac format be used as dataset

### ISSUE THREAD

**Issue by huangp0600** [yeyupiaoling/AudioClassification-Pytorch#23]
Great thanks for providing such an awesome project ！
I have a batch of audio files with flac format, can they used as dataset to run this project

**Comment by yeyupiaoling** [comment]
@huangp0600 Of course. Support wav, flac, mp3 .....

**Comment by huangp0600** [comment]
@yeyupiaoling  great thanks for quick reply. 
I have another question about model training. 
**case1**
I have 100 audio files, each with a duration of 20s
**case2**
I split each audio file to two parts. then I have 200 files totally, each with a duration of 10s.

which is better for training model, or which can achieve better accuracy?

**Comment by yeyupiaoling** [comment]
@huangp0600 case2
During training, the audio will be cropped automatically, but if you have a more reasonable cropping, it will be more beneficial to train the model.
