### ISSUE TITLE
RuntimeWarning when train

### ISSUE THREAD

**Issue by huangp0600** [yeyupiaoling/AudioClassification-Pytorch#24]
I got a warning when training, the detailed message is as follow
`
/data/aigc/speech/AudioClassification-Pytorch/macls/data_utils/audio.py:501: RuntimeWarning: divide by zero encountered in log10
  return 10 * np.log10(mean_square)
`
should it be noticed?

**Comment by yeyupiaoling** [comment]
It's not a big problem, don't worry
