### ISSUE TITLE
eval.py结果与测试集上使用predict得到的结果不相同

### ISSUE THREAD

**Issue by gaoxc315** [yeyupiaoling/AudioClassification-Pytorch#29]
通过使用predict循环预测测试集上的到的混淆矩阵
[[153  86]
[ 19  92]] 
但是通过eval脚本的到的混淆矩阵是
[[229  10]
 [ 60  52]]
两者相差还是比较大的，总数差一的原因是有个小于0.5s

**Comment by yeyupiaoling** [comment]
@gaoxc315 差异应该不会很大才对，你的评估准确率是多少？predict的准确率又是多少？
