### ISSUE TITLE
是否可以分享下其他音频特征处理代码

### ISSUE THREAD

**Issue by karryor** [yeyupiaoling/AudioClassification-Pytorch#32]
您好，是否可以分享下，当音频处理方法为MelSpectrogram、Spectrogram、MFCC时的音频处理代码逻辑，在您的fraturizer.py下，只看到了Fbank特征提取方法对应的代码，如下：
class KaldiFbank(nn.Module):
    def __init__(self, **kwargs):
        super(KaldiFbank, self).__init__()
        self.kwargs = kwargs

    def forward(self, waveforms):
        """
        :param waveforms: [Batch, Length]
        :return: [Batch, Length, Feature]
        """
        log_fbanks = []
        for waveform in waveforms:
            if len(waveform.shape) == 1:
                waveform = waveform.unsqueeze(0)
            log_fbank = Kaldi.fbank(waveform, **self.kwargs)
            log_fbank = log_fbank.transpose(0, 1)
            log_fbanks.append(log_fbank)
        log_fbank = torch.stack(log_fbanks)
        return log_fbank

**Comment by yeyupiaoling** [comment]
那个文件已经包含了，你具体看一下，是调用pytorch的
