### ISSUE TITLE
learning

### ISSUE THREAD

**Issue by sinofs** [yeyupiaoling/AudioClassification-Pytorch#4]
大佬，请教程序对同训练的类别完全不相关的声音如何反馈识别结果的？
当我使用infer_recoder.py这个程序的时候如果盖住话筒，系统仍然反馈识别结果是训练中的类别中的一个，但是类别很固定。

**Comment by yeyupiaoling** [comment]
可以对得分设置个阈值，如果得分不高于这个阈值，可以认为识别无效。
