### ISSUE TITLE
训练次数

### ISSUE THREAD

**Issue by SSTato** [yeyupiaoling/AudioClassification-Pytorch#8]
请问训练多少次比较合适，如何保留最优的模型，或者在最优结果时停止呢。

**Comment by SSTato** [comment]
![image](https://user-images.githubusercontent.com/93987794/182567749-e7c7e55c-70eb-4193-a074-2b4254dcb37c.png)
训练过程是否使用了GPU呢，为什么我一开始训练，cpu就占满了，调小batchsize也没用

**Comment by yeyupiaoling** [comment]
是指定GPU训练的，但是因为预处理用的是CPU，可能是这样原因

**Comment by SSTato** [comment]
> 是指定GPU训练的，但是因为预处理用的是CPU，可能是这样原因

这个问题该怎么解决呢

**Comment by yeyupiaoling** [comment]
音频预处理是必须的，这是正常情况

**Comment by SSTato** [comment]
> 音频预处理是必须的，这是正常情况

能不能把他转移到gpu上，避免占用太多cpu呢，我不太懂这个，就是提出一个想法

**Comment by yeyupiaoling** [comment]
不能，

**Comment by SSTato** [comment]
> 不能，

我如果训练自己录制的音频文件，需要先做降噪处理吗

**Comment by yeyupiaoling** [comment]
有降噪工具，最好使用

**Comment by SSTato** [comment]
> 有降噪工具，最好使用

请问准确率能有多少呢

**Comment by yeyupiaoling** [comment]
这个得训练才知道
