### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by SSTato** [yeyupiaoling/AudioClassification-Pytorch#9]
请问在训练自己的数据集的时候，我的音频是30s的，我要自己分割成若干子音频吗，比如3s一个，还是可以直接训练30s的就行，如果要分，多长一个比较好呢

**Comment by yeyupiaoling** [comment]
一般是3秒，太长不行的，会爆显存，对训练也没有用，下采样会丢很多信息

**Comment by yeyupiaoling** [comment]
长一点也行，就不要太长

**Comment by SSTato** [comment]
> 长一点也行，就不要太长

那一两秒呢，短了有影响吗

**Comment by yeyupiaoling** [comment]
小于于1秒会过滤掉
